### ISSUE TITLE
code review 

### ISSUE THREAD

**Issue by tls3254** [mingtian-chan/Hang99_Spring_intro#2]
좋은 점
date가 db그대로에 안들어가서 데이터의 변환을 주어서
만들었던것
order by를 쓰어서 내림 차순으로 만들었던것
혹시나 date값이 들어가지 않을까봐 삼항연산자를 쓰어서 date가 들어가게 한 것

고치면 좋은 점
삼항 연산자는 실전에서 잘 안쓰기 때문에 if- else를 쓰는 것

**Comment by mingtian-chan** [comment]
삼항 연산자를 썼는데, if문을 쓰는 편이 더 나을 것 같네요! 감사합니다.

추가로, else문을 빼고 timestamp가 데이터베이스에 없는 상황을 안 만드는 것이 나아보입니다! 

https://github.com/mingtian-chan/Hang99_Spring_intro/blob/c322567448fec3fa65945d6ae184153038521dee/board/src/main/java/com/sparta/board/controller/BoardController.java#L86-L90

이 부분이 timestamp가 없으면 지금 시간을 찍어주는 코드인데, 없으면 null이 리턴되는 방식이 나을 듯 합니다. 저장된 시간이 없다 하더라도, 지금 시간을 알려주는 것은 게시판의 의도와는 좀 다르니까요.
