### ISSUE TITLE
코드리뷰 

### ISSUE THREAD

**Issue by Crescent0kt** [mingtian-chan/Hang99_Spring_intro#3]
1. Controller - 보안 문제가 생기는 거로 알고 있어서.. password는 body에서 전송하는 것이 좋을 것 같습니다!
2. 전체적으로 기능이 조금 더 분리되면 좋을 것 같습니다!

**Comment by mingtian-chan** [comment]
1. 확인했습니다! requestBody에 넣어서 전송하는 방식으로 수정하겠습니다.

2. 경택님 코드 봤는데, 분리가 잘 되어있어서 참고해서 기능분리를 해보겠습니다!
